changelog:
  exclude:
    labels:
      - chore
  categories:
    - title: "🚀 New features"
      labels:
        - feature
    - title: "🐛 Bug fixes"
      labels:
        - bug
    - title: "⚡ Performance improvements"
      labels:
        - perf
    - title: "💥 Breaking changes"
      labels:
        - breaking
